-- Minimal source-compatible schema for local KUCS GenAI demo data.
-- This is intentionally limited to the columns consumed by sync-service.js.

CREATE TABLE IF NOT EXISTS app_category (
    id UUID PRIMARY KEY,
    "nameEn" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sub_category (
    id UUID PRIMARY KEY,
    app_category_id UUID REFERENCES app_category(id),
    "nameEn" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS apps (
    id UUID PRIMARY KEY,
    app_id UUID,
    name TEXT NOT NULL,
    mode TEXT,
    source TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    model JSONB,
    graph JSONB,
    sub_category_id UUID REFERENCES sub_category(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kucs_apps_app_id ON apps(app_id);
CREATE INDEX IF NOT EXISTS idx_kucs_apps_updated_at ON apps(updated_at);

CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY,
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "lastLogin" TIMESTAMPTZ,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "memberType" TEXT,
    "userInfo" JSONB
);

CREATE INDEX IF NOT EXISTS idx_kucs_user_updated_at ON "user"("updatedAt");

CREATE TABLE IF NOT EXISTS user_app_usage (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES "user"(id),
    app_id UUID REFERENCES apps(id),
    conversation_id TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    input_tokens BIGINT,
    output_tokens BIGINT,
    total_tokens BIGINT,
    total_price NUMERIC(20, 8),
    currency VARCHAR(10),
    exchange_rate NUMERIC(20, 8),
    vat_rate NUMERIC(10, 6),
    total_thb NUMERIC(20, 6),
    total_coins NUMERIC(20, 6),
    calculate_method VARCHAR(80)
);

CREATE INDEX IF NOT EXISTS idx_kucs_usage_updated_id ON user_app_usage(updated_at, id);
CREATE INDEX IF NOT EXISTS idx_kucs_usage_conversation ON user_app_usage(conversation_id);
CREATE INDEX IF NOT EXISTS idx_kucs_usage_app ON user_app_usage(app_id);
CREATE INDEX IF NOT EXISTS idx_kucs_usage_user ON user_app_usage(user_id);

CREATE TABLE IF NOT EXISTS ai_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES "user"(id),
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    tags JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kucs_notes_updated_id ON ai_notes("updatedAt", id);
CREATE INDEX IF NOT EXISTS idx_kucs_notes_owner ON ai_notes(owner_id);
